
clickhouse:
  host: "test-host"
  port: 8443
  username: "test-user"
  password: "test-pass"
  database: "test_db"
  secure: true

redis:
  url: "redis://test-host:6379/0"

kafka:
  bootstrap_servers: "test-host:9092"
  client_id: "test-client"

security:
  secret_key: "test-secret"
  algorithm: "HS256"
  access_token_expire_minutes: 30
  allowed_ips: ["127.0.0.1"]

debug_mode: true
log_level: "DEBUG"
