








# Security Configuration for AI_BackLog_Assistant

# Encryption settings
encryption:
  enabled: true
  # Key will be generated if not provided
  # key: "your-encryption-key-here"

# HMAC settings for data integrity
hmac:
  enabled: true
  # Key will be generated if not provided
  # key: "your-hmac-key-here"

# Token settings
tokens:
  expiration: 3600  # 1 hour in seconds
  # Secret will be generated if not provided
  # secret: "your-token-secret-here"

# API keys
api_keys:
  # Format: "api_key": "security_level"
  # Security levels: LOW, MEDIUM, HIGH, CRITICAL
  "DEFAULT_API_KEY": "MEDIUM"
  "ADMIN_API_KEY": "HIGH"

# IP allowlist
allowed_ips:
  - "127.0.0.1"  # localhost
  - "::1"        # localhost IPv6
  - "10.0.0.0/8" # Private network range
  - "192.168.0.0/16" # Private network range

# Rate limits (requests per minute)
rate_limits:
  login: 5       # 5 login attempts per minute
  api: 100       # 100 API requests per minute
  search: 50     # 50 search requests per minute

# Component communication settings
component_communication:
  timeout: 5     # 5 seconds timeout
  retry_attempts: 3
  retry_delay: 1 # 1 second between retries

# Audit logging
audit:
  enabled: true
  log_file: "audit.log"
  retention_days: 30

# Security alerts
alerts:
  enabled: true
  email_notifications: true
  slack_notifications: false
  alert_thresholds:
    failed_logins: 3
    unauthorized_access: 1
    data_breach: 1

# Certificate settings
certificates:
  # Paths to SSL certificates
  ssl_cert: "certs/server.crt"
  ssl_key: "certs/server.key"
  ca_cert: "certs/ca.crt"

# Password policy
password_policy:
  min_length: 12
  require_uppercase: true
  require_lowercase: true
  require_digits: true
  require_special: true
  max_attempts: 5
  lockout_time: 300  # 5 minutes in seconds

# Data retention policy
data_retention:
  logs: 90      # 90 days
  audit_logs: 365 # 1 year
  user_data: 1825 # 5 years

# Backup settings
backups:
  enabled: true
  frequency: "daily"
  retention: 30  # 30 days
  encryption: true
  storage:
    - "local"
    - "s3"
    - "azure"

# Compliance settings
compliance:
  gdpr: true
  hipaa: false
  pci_dss: false
  data_residency: "EU"

# Monitoring settings
monitoring:
  security_events: true
  anomaly_detection: true
  alerting: true

# Update: 2025-08-07
# Added comprehensive security configuration
# Implemented encryption, token management, and audit logging

